### ISSUE TITLE
KotF issues

### ISSUE THREAD

**Issue by Xerocoles** [Electroid/PGM#102]
In King of the Flag (Desert Sanctuary, Little China, Maple Syrup, etc.) you can place blocks even though it's conquest through a weird bug.  If you're on the team holding the flag, and you die, it doesn't let you respawn (that's normal like the gamemode) but then you can open your creative inventory and place blocks on the map. (not destroy) I think it _might_ only be happening when gamemode is set to adventure in the xml.

Also, the scoreboard doesn't show up at all in KotF, or at least for most people.  (I think maybe some people could see it for some reason but I don't believe it was related to versions)

**Comment by RuedigerLP** [comment]
On maps that don't use a kit with Adventure-Mode, you can't build but you can throw potions etc.

**Comment by Pugzy** [comment]
The lack of a scoreboard is caused by a casting exception.

https://github.com/Electroid/PGM/blob/ae0ad4750e80ce6266da1d914fdc89e69ad61283/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java#L292

```
java.lang.ClassCastException: tc.oc.pgm.match.Observers cannot be cast to tc.oc.pgm.api.party.Competitor
        at tc.oc.pgm.scoreboard.SidebarMatchModule.renderGoal(SidebarMatchModule.java:292) ~[?:?]
        at tc.oc.pgm.scoreboard.SidebarMatchModule.renderSidebar(SidebarMatchModule.java:393) ~[?:?]
        at tc.oc.pgm.scoreboard.SidebarMatchModule.access$100(SidebarMatchModule.java:54) ~[?:?]
        at tc.oc.pgm.scoreboard.SidebarMatchModule$1.run(SidebarMatchModule.java:336) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:891) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"374af6d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by Electroid** [comment]
Fixed ^
