### ISSUE TITLE
Fix invalid plugin.yml

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#13]
When loading PGM using the traditional `plugins/` folder approach, the `plugin.yml` cannot be loaded.

```
[06:52:36 ERROR]: Could not load 'plugins/pgm.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:238) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [sportpaper.jar:git-SportPaper-"374af6d"]
	at java.lang.Thread.run(Thread.java:819) [?:1.8.0_232]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_232]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_232]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_232]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_232]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	... 5 more
```

**Comment by Electroid** [comment]
Issue has been resolved in recent commits.
