### ISSUE TITLE
Fix compilation issues with jars

### ISSUE THREAD

**Issue by Electroid** [Electroid/PGM#22]
https://paste.ubuntu.com/p/Yj7xYWvp3r/

**Comment by Brottweiler** [comment]
The paste will expire so I am posting the stracktrace here too 
```java
[22:21:23 ERROR]: Could not load 'plugins/pgm.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: app/ashcon/intake/fluent/CommandGraph
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:238) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [sportpaper.jar:git-SportPaper-"374af6d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: app/ashcon/intake/fluent/CommandGraph
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: app.ashcon.intake.fluent.CommandGraph
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        ... 6 more
```
