### ISSUE TITLE
Unable to join a team

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#55]
When a regular user runs `/join` they are greeted with an error, and the console shows the error below.

I can run `/join`, maybe because I am OP, but the game doesn't start and if I try to join obs, it tells me I am already observing.

```java
java.lang.NullPointerException
       at tc.oc.pgm.join.JoinMatchModule.queryJoin(JoinMatchModule.java:84)
       at tc.oc.pgm.join.JoinMatchModule.join(JoinMatchModule.java:142)
       at tc.oc.pgm.commands.JoinCommands.join(JoinCommands.java:53)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at app.ashcon.intake.parametric.MethodCallable.call(MethodCallable.java:106)
       at app.ashcon.intake.parametric.AbstractParametricCallable$1.call(AbstractParametricCallable.java:215)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
       at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58)
       at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
       at app.ashcon.intake.parametric.CommandExecutorWrapper.submit(CommandExecutorWrapper.java:42)
       at app.ashcon.intake.parametric.AbstractParametricCallable.call(AbstractParametricCallable.java:212)
       at app.ashcon.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:140)
       at app.ashcon.intake.CommandCallable.call(CommandCallable.java:67)
       at app.ashcon.intake.bukkit.BukkitIntake.onCommand(BukkitIntake.java:109)
       at app.ashcon.intake.bukkit.command.BukkitCommand.execute(BukkitCommand.java:50)
       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:650)
       at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1331)
       at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1143)
       at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
       at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
       at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
       at net.minecraft.server.v1_8_R3.MinecraftServer.processTasks(MinecraftServer.java:1724)
       at net.minecraft.server.v1_8_R3.DedicatedServer.processTasks(DedicatedServer.java:397)
       at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:882)
       at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365)
       at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821)
       at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722)
       at java.lang.Thread.run(Thread.java:748)
```

**Comment by Electroid** [comment]
Fixed in https://github.com/Electroid/PGM/commit/11affbc18e7d05c13784b2e1a099042b7e91a96f

Essentially, the issue was `Competitor#isObserving` returns true before a `Match` starts. That still holds true, but there were some places in the code that I had assumed `isObserving == ObservingParty`. Rookie mistake.
