### ISSUE TITLE
Game is broken

### ISSUE THREAD

**Issue by ChemistryX** [Electroid/PGM#58]
```
[17:04:31] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PGM v1.8-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) [sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) [sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) [sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:319) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:177) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:161) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:62) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:232) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:172) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:977) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"374af6d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: Party is not in this match and cannot be automatically added
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at tc.oc.pgm.match.MatchImpl.setOrClearPlayerParty(MatchImpl.java:428) ~[?:?]
	at tc.oc.pgm.match.MatchImpl.setParty(MatchImpl.java:400) ~[?:?]
	at tc.oc.pgm.match.MatchImpl.addPlayer(MatchImpl.java:384) ~[?:?]
	at tc.oc.pgm.listeners.PGMListener.addPlayerOnJoin(PGMListener.java:77) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	... 18 more
```

The whole game is broken after this happens.
This occurs after 5a5ad2e4423ee588683b213dd37ed59c655be7d5.

**Comment by Brottweiler** [comment]
I noticed my server console was spammed with these errors last night as well.

**Comment by Brottweiler** [comment]
Actually, my console was spammed with this, not sure if related

```java
[03:29:01 ERROR]: Could not pass event EntityExplodeEvent to PGM v1.8-SNAPSHOT
org.bukkit.event.EventException
        at tc.oc.pgm.listeners.BlockTransformListener$1.execute(BlockTransformListener.java:95) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:65) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.callEventHandler(SimplePluginManager.java:569) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.dispatchEvent(SimplePluginManager.java:534) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.callEventSynchronously(SimplePluginManager.java:527) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:521) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:201) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:2026) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1059) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:113) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.EntityTNTPrimed.t_(EntityTNTPrimed.java:87) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1703) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1670) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1503) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:948) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"374af6d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
```

**Comment by Electroid** [comment]
Pushed a fix here: https://github.com/Electroid/PGM/commit/7bd926149716816901ac63c7c7a7f1dca142a70d

Hopefully this will be fixed, but not too sure yet.

**Comment by Brottweiler** [comment]
@Electroid after that commit, the console not only says this twice
```
[17:29:09 INFO]: Currently playing Warlock by McSpider
[17:29:09 INFO]: Currently playing Warlock by McSpider
```

when stopping the server, this error appears
```java
[17:29:30 ERROR]: Error occurred while disabling PGM v1.8-SNAPSHOT (Is it up to date?)
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_222]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_222]
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044) ~[?:1.8.0_222]
        at tc.oc.pgm.PGM.onDisable(PGM.java:282) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327) ~[sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [sportpaper.jar:git-SportPaper-"374af6d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:284) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:480) [sportpaper.jar:git-SportPaper-"374af6d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:760) [sportpaper.jar:git-SportPaper-"374af6d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by Brottweiler** [comment]
Maybe related to my comment about when it shows "currently playing" twice, sometimes this happens also

```
[14:19:02 INFO]: Cycling to Spaceship Battles in 30 seconds
[14:19:12 INFO]: Cycling to Spaceship Battles in 20 seconds
[14:19:22 INFO]: Cycling to Spaceship Battles in 10 seconds
[14:19:24 INFO]: Currently playing Medieval Warfare
[14:19:24 INFO]: Currently playing Airship Battle by dewtroid
[14:19:24 INFO]: Currently playing Sunrise Over Paradise
[14:19:24 INFO]: Currently playing Tree of Life
[14:19:24 INFO]: Currently playing Warlock by McSpider
[14:19:24 INFO]: Currently playing Sunrise Over Paradise
[14:19:24 INFO]: Currently playing Tree of Life
[14:19:24 INFO]: Currently playing Warlock by McSpider
[14:19:24 INFO]: Currently playing Medieval Warfare
[14:19:24 INFO]: Currently playing Airship Battle by dewtroid
[14:19:27 INFO]: Cycling to Spaceship Battles in 5 seconds
[14:19:28 INFO]: Cycling to Spaceship Battles in 4 seconds
[14:19:29 INFO]: Cycling to Spaceship Battles in 3 seconds
[14:19:30 INFO]: Cycling to Spaceship Battles in 2 seconds
[14:19:31 INFO]: Cycling to Spaceship Battles in 1 second
```

**Comment by Electroid** [comment]
That issues is part of #72

**Comment by TheMolkaPL** [comment]
I wouldn't close this. Matches aren't removed on cycle.

**Comment by Electroid** [comment]
Are the matches not getting removed, leaking, or something else?

**Comment by TheMolkaPL** [comment]
Diff before and after 5a5ad2e4423ee588683b213dd37ed59c655be7d5:

https://github.com/Electroid/PGM/blob/cd7feaa8fcbe39d24c6b757be0cd82706f94cbbd/src/main/java/tc/oc/pgm/match/MatchManager.java#L394-L402

https://github.com/Electroid/PGM/blob/5a5ad2e4423ee588683b213dd37ed59c655be7d5/src/main/java/tc/oc/pgm/match/MatchManagerImpl.java#L274-L278

`unloadMatch` isn't called anymore except in [JavaPlugin.onDisable](https://github.com/Electroid/PGM/blob/5a5ad2e4423ee588683b213dd37ed59c655be7d5/src/main/java/tc/oc/pgm/PGM.java#L283) and when [new match fails to load](https://github.com/Electroid/PGM/blob/5a5ad2e4423ee588683b213dd37ed59c655be7d5/src/main/java/tc/oc/pgm/match/MatchManagerImpl.java#L71).

**Comment by TheMolkaPL** [comment]
@Brottweiler https://github.com/Electroid/PGM/issues/58#issuecomment-551106842 This leads to point where NPE is thrown with a parent exception. Please check your logs and send the complete stack trace.
