### ISSUE TITLE
Custom crafting not working

### ISSUE THREAD

**Issue by ChemistryX** [Electroid/PGM#68]
```
[PGM] Task #58 for PGM v1.8-SNAPSHOT generated an exception
java.lang.NullPointerException
	at tc.oc.pgm.crafting.CraftingMatchModule.enable(CraftingMatchModule.java:33) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_221]
	at tc.oc.pgm.match.MatchImpl.setPhase(MatchImpl.java:159) ~[?:?]
	at tc.oc.pgm.api.match.Match.start(Match.java:154) ~[?:?]
	at tc.oc.pgm.start.StartCountdown.onEnd(StartCountdown.java:99) ~[?:?]
	at tc.oc.pgm.countdowns.CountdownRunner.run(CountdownRunner.java:141) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[sportpaper.jar:git-SportPaper-"374af6d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:891) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:821) [sportpaper.jar:git-SportPaper-"374af6d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:722) [sportpaper.jar:git-SportPaper-"374af6d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

**Comment by Electroid** [comment]
Fixed ^
